SERVICE_PORT: 8199
SERVICE_NAME: dff_jtjcrpd68is1_prompted_skill
PROMPT_FILE: common/prompts/jtjcrpd68is1.json
GENERATIVE_SERVICE_URL: http://gigachat-api:8187/respond
GENERATIVE_SERVICE_CONFIG: jtjcrpd68is1.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION,GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
