name: sentrewrite
endpoints:
- sentrewrite
compose:
  env_file:
  - .env
  build:
    context: ./annotators/SentRewrite/
  command: flask run -h 0.0.0.0 -p 8017
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 512M
  volumes:
  - ./annotators/SentRewrite:/src
  ports:
  - 8017:8017
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8017
  - PORT=8017
