SERVICE_PORT: 8002
SERVICE_NAME: response_selector
SENTENCE_RANKER_ANNOTATION_NAME: sentence_ranker
SENTENCE_RANKER_SERVICE_URL: http://sentence-ranker:8128/respond
SENTENCE_RANKER_TIMEOUT: 3
N_UTTERANCES_CONTEXT: 5
ENABLE_FACT_CHECKING: 1
FACTUAL_CONFORMITY_SERVICE_URL: http://fact-checking:8182/respond
FACTUAL_CONFORMITY_SERVICE_TIMEOUT: 5
FACTUAL_CONFORMITY_ANNOTATION_NAME: fact_checking
FILTER_TOXIC_OR_BADLISTED: 1
FLASK_APP: server
