name: ranking-based-response-selector-fact-checking
endpoints:
- respond
compose:
  env_file: [ .env ]
  build:
    args:
      SERVICE_PORT: 8002
      SERVICE_NAME: response_selector
      LANGUAGE: EN
      SENTENCE_RANKER_ANNOTATION_NAME: sentence_ranker
      SENTENCE_RANKER_SERVICE_URL: http://sentence-ranker:8128/respond
      SENTENCE_RANKER_TIMEOUT: 3
      ENABLE_FACT_CHECKING: 1
      FACTUAL_CONFORMITY_SERVICE_URL: http://fact-checking:8182/respond
      FACTUAL_CONFORMITY_SERVICE_TIMEOUT: 5
      FACTUAL_CONFORMITY_ANNOTATION_NAME: fact_checking
      N_UTTERANCES_CONTEXT: 5
      FILTER_TOXIC_OR_BADLISTED: 1
      FLASK_APP: server
    context: .
    dockerfile: ./response_selectors/ranking_based_response_selector/Dockerfile
  command: flask run -h 0.0.0.0 -p 8002
  environment:
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  ports:
  - 8002:8002
proxy: null
