name: dff-api-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8168
      SERVICE_NAME: dff_api_skill
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 15
      N_UTTERANCES_CONTEXT: 1
      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
    context: .
    dockerfile: ./skills/dff_api_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8168 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_api_skill:/src
  - ./common:/src/common
  - "./skills/dff_weather_skill/tools:/src/tools"
  - "./skills/dff_weather_skill/data:/src/data"
  ports:
  - 8168:8168
proxy: null
