SERVICE_PORT: 8144
SERVICE_NAME: dff_fashion_stylist_prompted_skill
PROMPT_FILE: common/prompts/fashion_stylist.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
