SERVICE_PORT: 8189
SERVICE_NAME: dff_general_pm_prompted_skill
PROMPT_FILE: common/prompts/general_pm.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt-long.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
