convers-evaluator-annotator:
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://convers-evaluator-annotator:8004/batch_model
  dialog_formatter: state_formatters.dp_formatters:convers_evaluator_annotator_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
