name: dff-knowledge-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8137
      SERVICE_NAME: dff_knowledge_prompted_skill
      PROMPT_FILE: common/prompts/dream_persona.json
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
      USER_KG_SERVICE_URL: http://user-knowledge-graph:8129/respond
      ENVVARS_TO_SEND: OPENAI_API_KEY
      USE_BOT_KG_DATA: 1
    context: .
    dockerfile: ./skills/dff_knowledge_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_knowledge_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8137:8137
proxy: null
