dff-reasoning-skill:
- group: skills
  connector:
    protocol: http
    timeout: 30.0
    url: http://dff-reasoning-skill:8169/respond
  dialog_formatter:
    name: state_formatters.dp_formatters:dff_prompted_skill_formatter
    skill_name: dff_reasoning_skill
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis