name: ros-flask-server
endpoints:
- is_command_valid
- perform_command
- is_command_performed
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 5000
      SERVICE_NAME: ros_flask_server
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./services/ros_flask_server/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:5000 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 2G
  volumes:
  - ./common:/src/common
  - ./services/ros_flask_server:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 5000:5000