SERVICE_PORT: 8003
SERVICE_NAME: response_selector
LANGUAGE: EN
GENERATIVE_SERVICE_URL: http://openai-api-gpt4:8159/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt-short.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 1
CHOOSE_HYP_BY_NUM: 1
FILTER_TOXIC_OR_BADLISTED: 0
PROMPT_FILE: common/prompts/response_selector_by_number.json
FLASK_APP: server
