# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  spacy-nounphrases:
    volumes:
      - "./annotators/spacy_nounphrases:/src"
      - "./common:/src/common"
    ports:
      - 8006:8006
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  intent-catcher-commands:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8014:8014
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  dialogpt:
    volumes:
      - "./common:/src/common"
      - "./services/dialogpt:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8125:8125
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8103:8103
  ner:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  ros-flask-server:
    volumes:
      - "./services/ros_flask_server:/home/dkr/"
      - "./common:/home/dkr/common"
    ports:
      - 6000:6000
  dff-command-selector-skill:
    volumes:
      - "./skills/dff_command_selector_skill:/src"
      - "./common:/src/common"
    ports:
      - 8148:8148
  robot-command-sender:
    volumes:
      - "./services/robot_command_sender:/src"
      - "./common:/src/common"
    ports:
      - 8035:8035
  robot-fake-server:
    volumes:
      - "./services/robot_fake_server:/src"
      - "./common:/src/common"
    ports:
      - 8038:8038
  robot-notifications:
    volumes:
      - "./services/robot_notifications:/src"
      - "./common:/src/common"
    ports:
      - 8036:8036

version: "3.7"
