user-persona-extractor:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://user-persona-extractor:8114/respond
  dialog_formatter: state_formatters.dp_formatters:utt_non_punct_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  state_manager_method: update_attributes
