prompt-selector:
- group: annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://prompt-selector:8135/respond
  dialog_formatter: state_formatters.dp_formatters:context_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  state_manager_method: add_annotation
