agent:
- group: skills
  connector:
    protocol: python
    class_name: skills.dummy_skill.connector:DummySkillConnector
  dialog_formatter: state_formatters.dp_formatters:utt_sentrewrite_modified_last_dialog
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
