name: dff-mint-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8337
      SERVICE_NAME: dff_mint_skill
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./skills/dff_mint_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8337 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 2G
  volumes:
  - ./common:/src/common
  - ./skills/dff_mint_skill:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8337:8337