news-api-annotator:
- group: annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://news-api-annotator:8112/respond
  dialog_formatter: state_formatters.dp_formatters:utt_non_punct_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  - annotators.ner
  - annotators.entity_detection
  - annotators.spacy_nounphrases
  state_manager_method: add_annotation
