SERVICE_PORT: 8141
SERVICE_NAME: dff_nutrition_prompted_skill
PROMPT_FILE: common/prompts/nutrition.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
