SERVICE_PORT: 8182
SERVICE_NAME: skill_selector
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt-short.json
GENERATIVE_TIMEOUT: 10
N_UTTERANCES_CONTEXT: 3
N_TURNS_TO_KEEP_DOC: 5
PROMPT_FILE: common/prompts/skill_selector.json
FLASK_APP: server