name: emotional-bot-response
endpoints:
- respond_batch
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8050
      SERVICE_NAME: emotional_bot_response
      WORK_DIR: annotators/emotional_bot_response
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 30.0
      N_UTTERANCES_CONTEXT: 1
      ENVVARS_TO_SEND: OPENAI_API_KEY
    context: .
    dockerfile: annotators/emotional_bot_response/Dockerfile
  command: flask run -h 0.0.0.0 -p 8050
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 500M
      reservations:
        memory: 100M
  volumes:
  - ./annotators/emotional_bot_response:/src
  - ./common:/src/common
  ports:
  - 8050:8050
