fact-retrieval:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://fact-retrieval:8100/model
  dialog_formatter: state_formatters.dp_formatters:fact_retrieval_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  - annotators.entity_linking
  state_manager_method: add_annotation
