seq2seq-persona-based:
- group: skills
  connector:
    protocol: http
    timeout: 3.0
    url: http://seq2seq-persona-based:8140/respond
  dialog_formatter: state_formatters.dp_formatters:persona_bot_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
