services:
  agent:
    ports:
    - 4242:4242
    volumes:
    - .:/dp-agent
  convers-evaluator-annotator:
    volumes:
      - "./annotators/ConversationEvaluator:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8004:8004
  badlisted-words:
    ports:
    - 8018:8018
    volumes:
    - ./annotators/BadlistedWordsDetector:/src
    - ./common:/src/common
  convers-evaluation-selector:
    ports:
    - 8009:8009
    volumes:
    - ./response_selectors/convers_evaluation_based_selector:/src
    - ./common:/src/common
  dff-template-skill:
    ports:
    - 8120:8120
    volumes:
    - ./skills/dff_template_skill:/src
    - ./common:/src/common
  dff-language-practice-skill:
    ports:
    - 8130:8130
    volumes:
    - ./skills/dff_language_practice_skill:/src
    - ./common:/src/common
  dff-mistakes-review-skill:
    ports:
    - 8131:8131
    volumes:
    - ./skills/dff_mistakes_review_skill:/src
    - ./skills/dff_language_practice_skill/data:/src/data
    - ./common:/src/common
  mongo:
    ports:
    - 27017:27017
  sentseg:
    ports:
    - 8011:8011
    volumes:
    - ./annotators/SentSeg:/src
  language-mistakes-tracker:
    ports:
    - 8129:8129
    volumes:
    - ./annotators/language_mistakes_tracker:/src
    - ./skills/dff_language_practice_skill/data:/src/data
    - ./common:/src/common
  gector:
    volumes:
      - ./annotators/gector:/src
      - ./data:/data
      - ./common_packages:/common_packages
    ports:
      - 2102:2102
  dff-friendship-skill:
    volumes:
      - "./skills/dff_friendship_skill:/src"
      - "./common:/src/common"
    ports:
      - 8086:8086
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
    ports:
      - 8128:8128
version: '3.7'
