name: mint-sender
endpoints:
- send
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8338
      SERVICE_NAME: mint_sender
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./services/mint_sender/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8338 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 2G
  volumes:
  - ./common:/src/common
  - ./services/mint_sender:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8338:8338