services:

  sentseg:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8011
      - PORT=8011

  badlisted-words:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8018
      - PORT=8018

  spelling-preprocessing:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8074
      - PORT=8074

  # convers-evaluation-selector:
  #   command: [ "nginx", "-g", "daemon off;" ]
  #   build:
  #     context: dp/proxy/
  #     dockerfile: Dockerfile
  #   environment:
  #     - PROXY_PASS=dream.deeppavlov.ai:8009
  #     - PORT=8009

  combined-classification:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8087
      - PORT=8087

  chatgpt:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    extra_hosts:
      - "ai-rig:${HOST_GATEWAY}"
    environment:
      - PROXY_PASS=ai-rig:9150
      - PORT=8150

version: '3.7'
