SERVICE_PORT: 8157
SERVICE_NAME: dff_plan_for_article_prompted_skill
PROMPT_FILE: common/prompts/plan_for_article.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
