name: dff-plan-for-article-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8157
      SERVICE_NAME: dff_plan_for_article_prompted_skill
      PROMPT_FILE: common/prompts/plan_for_article.json
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8157:8157
proxy: null
