name: universal-llm-based-skill-selector
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8187
      SERVICE_NAME: skill_selector
      DEFAULT_LM_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      DEFAULT_LM_SERVICE_CONFIG: openai-chatgpt-short.json
      DEFAULT_LM_SERVICE_TIMEOUT: 10
      N_UTTERANCES_CONTEXT: 1
      N_TURNS_TO_KEEP_DOC: 5
      FLASK_APP: server
    context: .
    dockerfile: ./skill_selectors/universal_llm_based_skill_selector/Dockerfile
  command: flask run -h 0.0.0.0 -p 8187
  environment:
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  ports:
  - 8187:8187
proxy: null

