name: ranking-and-intent-based-response-selector-ru
endpoints:
- respond
compose:
  env_file: [ .env ]
  build:
    args:
      SERVICE_PORT: 8082
      SERVICE_NAME: response_selector
      SENTENCE_RANKER_ANNOTATION_NAME: dialogrpt
      SENTENCE_RANKER_SERVICE_URL: http://dialogrpt-ru:8122/rank_sentences
      SENTENCE_RANKER_TIMEOUT: 3
      N_UTTERANCES_CONTEXT: 5
      FILTER_TOXIC_OR_BADLISTED: 1
      FLASK_APP: server
    context: .
    dockerfile: ./response_selectors/ranking_and_intent_based_response_selector/Dockerfile
  command: flask run -h 0.0.0.0 -p 8082
  environment:
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  ports:
  - 8082:8082
proxy: null
