name: personality-detection
endpoints:
- model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8026
      SERVICE_NAME: personality_detection
    context: .
    dockerfile: ./annotators/personality_detection/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8026
  deploy:
    resources:
      limits:
        memory: 312M
      reservations:
        memory: 312M
  volumes:
  - ./annotators/personality_detection:/src
  ports:
  - 8026:8026