name: doc-retriever
endpoints:
  - vectorize_documents
  - return_candidates
compose:
  env_file:
    - .env
  build:
    args:
      SERVICE_PORT: 8165
      SERVICE_NAME: doc_retriever
      CONFIG_PATH: ./doc_retriever_config.json
      PARAGRAPHS_NUM: 5
      FILE_SERVER_TIMEOUT: 30.0
    context: .
    dockerfile: annotators/doc_retriever/Dockerfile
  command: flask run -h 0.0.0.0 -p 8165
  environment:
    - CUDA_VISIBLE_DEVICES=0
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 10G
      reservations:
        memory: 10G
  volumes:
    - "./annotators/doc_retriever:/src"
    - "./common:/src/common"
    - "./documents:/src/documents"
  ports:
    - 8165:8165
proxy: null
