name: doc-retriever
endpoints:
  - train_and_upload_model
  - return_candidates
compose:
  env_file:
    - .env
  build:
    args:
      SERVICE_PORT: 8165
      SERVICE_NAME: doc_retriever
      CONFIG_PATH: ./doc_retriever_config.json
      DOC_PATH_OR_LINK: http://files.deeppavlov.ai/dream_data/documents_for_qa/the_little_prince_book.txt,http://files.deeppavlov.ai/dream_data/documents_for_qa/alphabet_financial_report.txt,http://files.deeppavlov.ai/dream_data/documents_for_qa/apple_financial_report.txt
    context: ./annotators/doc_retriever/
  command: flask run -h 0.0.0.0 -p 8165
  environment:
    - CUDA_VISIBLE_DEVICES=0
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 3.5G
      reservations:
        memory: 3.5G
  volumes:
    - "./annotators/doc_retriever:/src"
    - "./common:/src/common"
  ports:
    - 8165:8165
proxy:
  command:
    - nginx
    - -g
    - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
    - PROXY_PASS=dream.deeppavlov.ai:8165
    - PORT=8165
