badlisted-words-ru:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://badlisted-words-ru:8018/badlisted_words
  dialog_formatter: state_formatters.dp_formatters:preproc_and_tokenized_last_human_utt_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.spacy_annotator
  state_manager_method: add_annotation
