name: dff-emo-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8999
      SERVICE_NAME: dff_emo_skill
    context: .
    dockerfile: ./skills/dff_emo_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8999 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_emo_skill:/src
  - ./common:/src/common
  ports:
  - 8999:8999
