SERVICE_PORT: 8137
SERVICE_NAME: dff_bot_knowledge_prompted_skill
PROMPT_FILE: common/prompts/knowledge.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY
USE_BOT_KG_DATA: 1