name: agent
endpoints:
- respond
compose:
  command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/universal_selectors_assistant/pipeline_conf.json'
  environment:
    WAIT_HOSTS: ''
    WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1000}
    LANGUAGE: EN
    FALLBACK_FILE: fallbacks_sentius_en.json
    FALLBACK_TO_DOCS_FILE: fallbacks_sentius_en_docs.json
  volumes:
  - .:/dp-agent
  ports:
  - 4242:4242
proxy: null
