SERVICE_PORT: 8199
SERVICE_NAME: dff_vs8v91cf94yl_prompted_skill
PROMPT_FILE: common/prompts/vs8v91cf94yl.json
GENERATIVE_SERVICE_URL: http://gigachat-api:8187/respond
GENERATIVE_SERVICE_CONFIG: vs8v91cf94yl.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION,GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
