dff-short-story-skill:
- group: skills
  connector:
    protocol: http
    timeout: 3.0
    url: http://dff-short-story-skill:8057/respond
  dialog_formatter: state_formatters.dp_formatters:dff_short_story_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
