SERVICE_PORT: 8172
SERVICE_NAME: dff_9vcrwpl06a47_prompted_skill
PROMPT_FILE: common/prompts/9vcrwpl06a47.json
GENERATIVE_SERVICE_URL: http://transformers-lm-ruxglm:8171/respond
GENERATIVE_SERVICE_CONFIG: 9vcrwpl06a47.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION,GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
