speech-function-classifier:
- group: annotators
  connector:
    protocol: http
    timeout: 5.0
    url: http://speech-function-classifier:8108/model
  dialog_formatter: state_formatters.dp_formatters:speech_function_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.sentseg
  - response_annotators.speech_function_classifier
  state_manager_method: add_annotation
- group: response_annotators
  connector:
    protocol: http
    timeout: 5.0
    url: http://speech-function-classifier:8108/model
  dialog_formatter: state_formatters.dp_formatters:speech_function_bot_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - response_annotator_selectors
  - response_annotators.sentseg
  state_manager_method: add_annotation_prev_bot_utt
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 5.0
    url: http://speech-function-classifier:8108/annotation
  dialog_formatter: state_formatters.dp_formatters:speech_function_annotation
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
