CONFIG_T5: t5_generative_ie_lite_infer.json
CONFIG_REL_RANKER: rel_ranking_roberta.json
SERVICE_PORT: 8136
SRC_DIR: annotators/property_extraction/
SERVICE_NAME: property_extraction
FLASK_APP: server
