name: mint-status
endpoints:
- check
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8340
      SERVICE_NAME: mint_status
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./annotators/mint_status/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8340 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 2G
  volumes:
  - ./common:/src/common
  - ./annotators/mint_status:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8340:8340