SERVICE_PORT: 8186
SERVICE_NAME: dff_meeting_analysis_skill
GENERATIVE_SERVICE_URL: http://openai-api-gpt4:8159/respond
GENERATIVE_SERVICE_CONFIG: openai-gpt4-long.json
GENERATIVE_TIMEOUT: 120
SHORT_GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
SHORT_GENERATIVE_SERVICE_CONFIG: openai-chatgpt-long.json
SHORT_GENERATIVE_TIMEOUT: 30
N_UTTERANCES_CONTEXT: 7
FILE_SERVER_TIMEOUT: 30.0
TRANSCRIPTOR_SERVICE_URL: 'http://3.86.192.202:8171'
BEARER_TOKEN_MICROSOFT_API: 'Bearer 6ad07e35-bb74-4683-a6f5-8c3bd31c0159'
