name: emotion-ranking-based-response-selector
endpoints:
- respond
compose:
  env_file: [ .env ]
  build:
    args:
      SERVICE_PORT: 8048
      SERVICE_NAME: response_selector
      LANGUAGE: EN
      SENTENCE_RANKER_ANNOTATION_NAME: sentence_ranker
      SENTENCE_RANKER_SERVICE_URL: http://sentence-ranker:8128/respond
      SENTENCE_RANKER_TIMEOUT: 3
      N_UTTERANCES_CONTEXT: 5
      FILTER_TOXIC_OR_BADLISTED: 1
      EMOTIONAL_RESPONSES: 1
    context: .
    dockerfile: ./response_selectors/emotion_ranking_based_response_selector/Dockerfile
  command: flask run -h 0.0.0.0 -p 8048
  environment:
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  ports:
  - 8048:8048
proxy: null
