services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  dff-program-y-skill:
  convers-evaluation-selector:
  dff-intent-responder-skill:
  dff-generative-skill:
  intent-catcher:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  badlisted-words:
  toxic-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  ner:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  personal-info-skill:
  entity-linking:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  wiki-parser:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  spelling-preprocessing:
  dff-friendship-skill:
  entity-detection:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  sentseg:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  dialogpt:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  dialogrpt:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  dff-template-skill:
  fact-retrieval:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  text-qa:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=8
version: '3.7'
