combined-classification:
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://combined-classification:8087/batch_model
  dialog_formatter: state_formatters.dp_formatters:hypothesis_histories_list
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
- group: annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://combined-classification:8087/model
  dialog_formatter: state_formatters.dp_formatters:preproc_last_human_utt_dialog_w_hist
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  state_manager_method: add_annotation
