agent:
- group: skill_selectors
  connector:
    protocol: python
    class_name: skill_selectors.rule_based_selector.connector:RuleBasedSkillSelectorConnector
  dialog_formatter: state_formatters.dp_formatters:base_skill_selector_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators
  tags:
  - selector
