# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  gpt2-generator:
    volumes:
      - "./services/gpt2_generator:/src"
    ports:
      - 8132:8132
  toxic-classification:
    volumes:
      - "./annotators/MultilingualToxicClassification:/src"
    ports:
      - 8013:8013
  sentiment-classification:
    volumes:
      - "./annotators/MultilingualSentimentClassification:/src"
    ports:
      - 8024:8024
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
    ports:
      - 8128:8128
version: "3.7"
