dff-intent-responder-skill:
- group: skills
  connector:
    protocol: http
    timeout: 2.0
    url: http://dff-intent-responder-skill:8012/respond
  dialog_formatter: state_formatters.dp_formatters:dff_intent_responder_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-intent-responder-ru-skill:
- group: skills
  connector:
    protocol: http
    timeout: 2.0
    url: http://dff-intent-responder-ru-skill:8012/respond
  dialog_formatter: state_formatters.dp_formatters:dff_intent_responder_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
