spelling-preprocessing-ru:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://spelling-preprocessing-ru:8074/respond
  dialog_formatter: state_formatters.dp_formatters:last_utt_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  state_manager_method: add_annotation_and_reset_human_attributes_for_first_turn
