SERVICE_PORT: 8020
SRC_DIR: annotators/user_knowledge_memorizer/
SERVICE_NAME: user_knowledge_memorizer
FLASK_APP: server
TERMINUSDB_SERVER_URL: http://terminusdb-server:6363
TERMINUSDB_SERVER_PASSWORD: root
TERMINUSDB_SERVER_TEAM: admin
TERMINUSDB_SERVER_DB: user_knowledge_db
USER_KM_SERVICE_CONFIG: index_load_path.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_SERVICE_TIMEOUT: 5
SENTENCE_RANKER_URL: http://sentence-ranker:8128/respond
SENTENCE_RANKER_TIMEOUT: 5
RELEVANT_KNOWLEDGE_THRESHOLD: 0.5
ENVVARS_TO_SEND: OPENAI_API_KEY
USE_KG_DATA: 0