SERVICE_PORT: 8027
SRC_DIR: annotators/user_knowledge_memorizer/
SERVICE_NAME: user_knowledge_memorizer
FLASK_APP: server
TERMINUSDB_SERVER_URL: http://terminusdb-server:6363
TERMINUSDB_SERVER_PASSWORD: root
TERMINUSDB_SERVER_TEAM: admin
TERMINUSDB_SERVER_DB: user_knowledge_db
USER_KM_SERVICE_CONFIG: index_load_path.json
