SERVICE_PORT: 8138
SERVICE_NAME: dff_marketing_prompted_skill
PROMPT_FILE: common/prompts/marketing.json
GENERATIVE_SERVICE_URL: http://transformers-lm-gptj:8130/respond
GENERATIVE_SERVICE_CONFIG: default_generative_config.json
GENERATIVE_TIMEOUT: 10
N_UTTERANCES_CONTEXT: 7
