entity-detection:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://entity-detection:8103/respond
  dialog_formatter: state_formatters.dp_formatters:entity_detection_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://entity-detection:8103/respond_batch
  dialog_formatter: state_formatters.dp_formatters:hypotheses_list
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
