name: bot-knowledge-memorizer
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8044
      SRC_DIR: annotators/bot_knowledge_memorizer/
      SERVICE_NAME: bot_knowledge_memorizer
      TERMINUSDB_SERVER_URL: http://terminusdb-server:6363
      TERMINUSDB_SERVER_PASSWORD: root
      TERMINUSDB_SERVER_TEAM: admin
      TERMINUSDB_SERVER_DB: bot_knowledge_db
      BOT_KM_SERVICE_CONFIG: config.json
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      SENTENCE_RANKER_URL: http://sentence-ranker:8128/respond
      SENTENCE_RANKER_TIMEOUT: 5
      RELEVANT_KNOWLEDGE_THRESHOLD: 0.2
      ENVVARS_TO_SEND: OPENAI_API_KEY
      USE_BOT_KG_DATA: 1
    context: ./
    dockerfile: annotators/bot_knowledge_memorizer/Dockerfile
  command: flask run -h 0.0.0.0 -p 8044
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./annotators/bot_knowledge_memorizer:/src
  - ~/.deeppavlov:/root/.deeppavlov
  ports:
  - 8044:8044
proxy: null