dff-generative-ru-skill:
- group: skills
  connector:
    protocol: http
    timeout: 4.0
    url: http://dff-generative-ru-skill:8092/respond
  dialog_formatter: state_formatters.dp_formatters:dff_generative_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
