emotion-classification-deepy:
- group: response_annotators
  connector:
    protocol: python
    url: http://emotion-classification-deepy:8015/model
    class_name: assistant_dists.deepy_faq.connectors:BatchConnector
  dialog_formatter: state_formatters.dp_formatters:hypotheses_list
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
