name: dff-user-kg-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8132
      SERVICE_NAME: dff_user_kg_skill
    context: .
    dockerfile: ./skills/dff_user_kg_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8132
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 512M
  volumes:
  - ./skills/dff_user_kg_skill:/src
  - ./common:/src/common
  ports:
  - 8132:8132
proxy: null