SERVICE_PORT: 8182
SERVICE_NAME: fact_checking
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_TIMEOUT: 5
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
FLASK_APP: server
