name: fact-checking
endpoints:
  - respond_batch
compose:
  env_file:
    - .env, .env_secret
  build:
    args:
      SERVICE_PORT: 8182
      SERVICE_NAME: fact_checking
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_TIMEOUT: 5
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    context: .
    dockerfile: annotators/fact_checking/Dockerfile
  command: flask run -h 0.0.0.0 -p 8182
  environment:
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
    - "./annotators/fact_checking:/src"
    - "./common:/src/common"
  ports:
    - 8182:8182
proxy: null
