name: dff-image-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8188
      SERVICE_NAME: dff_image_skill
      LANGUAGE: EN
    context: .
    dockerfile: ./skills/dff_image_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8188 --reload
  deploy:
    resources:
      limits:
        memory: 1024M
      reservations:
        memory: 1024M
  volumes:
  - ./skills/dff_image_skill:/src
  - ./common:/src/common
  ports:
  - 8188:8188
proxy: null
