entity-detection-ru:
- group: annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://entity-detection-ru:8103/respond
  dialog_formatter: state_formatters.dp_formatters:entity_detection_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
