SERVICE_PORT: 8179
SERVICE_NAME: dff_robot_prompted_skill
PROMPT_FILE: common/prompts/robot.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
