name: dff-robot-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8179
      SERVICE_NAME: dff_robot_prompted_skill
      PROMPT_FILE: common/prompts/robot.json
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8179:8179
proxy: null
