SERVICE_PORT: 8186
SERVICE_NAME: dff_document_qa_llm_skill
GENERATIVE_SERVICE_URL: http://transformers-lm-mistral-7b-128k:8185/respond
GENERATIVE_SERVICE_CONFIG: transformers_mistral.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
FILE_SERVER_TIMEOUT: 30
DOCUMENT_PROMPT_FILE: common/prompts/document_qa_instruction.json
