ner:
- group: annotators
  connector:
    protocol: http
    timeout: 1.5
    url: http://ner:8021/ner
  dialog_formatter: state_formatters.dp_formatters:ner_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
- group: response_annotators
  connector:
    protocol: http
    timeout: 1.5
    url: http://ner:8021/ner
  dialog_formatter: state_formatters.dp_formatters:ner_formatter_last_bot_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - response_annotator_selectors
  - response_annotators.sentseg
  state_manager_method: add_annotation_prev_bot_utt
ner-ru:
- group: annotators
  connector:
    protocol: http
    timeout: 1.5
    url: http://ner-ru:8021/ner
  dialog_formatter: state_formatters.dp_formatters:ner_formatter_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - annotators.spelling_preprocessing
  - annotators.sentseg
  state_manager_method: add_annotation
- group: response_annotators
  connector:
    protocol: http
    timeout: 1.5
    url: http://ner-ru:8021/ner
  dialog_formatter: state_formatters.dp_formatters:ner_formatter_last_bot_dialog
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - response_annotator_selectors
  - response_annotators.sentseg
  state_manager_method: add_annotation_prev_bot_utt
