agent:
- group: skills
  connector:
    protocol: python
    class_name: skills.alexa_handler.connector:AlexaHandlerConnector
  dialog_formatter: state_formatters.dp_formatters:last_utt_dialog
  response_formatter: state_formatters.dp_formatters:cobot_qa_formatter_service
  previous_services:
    - skill_selectors
  state_manager_method: add_hypothesis
