name: dff-book-sfc-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8034
      SERVICE_NAME: dff_book_skill
      QUERY_DICT: http://files.deeppavlov.ai/alexaprize_data/book_query_dict.pkl
    context: .
    dockerfile: ./skills/dff_book_sfc_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8034 --reload
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 512M
  volumes:
  - ./skills/dff_book_sfc_skill:/src
  - ./common:/src/common
  ports:
  - 8034:8034
proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8034
  - PORT=8034
