name: dff_aabgc9n0jdjm_prompted_skill
endpoints:
- respond
compose:
  image: null
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  env_file:
  - .env
  build:
    args: null
    context: .
    dockerfile: skills/dff_template_prompted_skill/Dockerfile
  command: null
  environment: null
  deploy:
    mode: null
    replicas: null
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  tty: null
  ports: null
proxy: null
