WAIT_HOSTS: ''
WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}
HIGH_PRIORITY_INTENTS: 1
RESTRICTION_FOR_SENSITIVE_CASE: 1
ALWAYS_TURN_ON_ALL_SKILLS: 0
ENABLE_NP_QUESTIONS: 1
ENABLE_SWITCH_TOPIC: 1
ENABLE_LINK_QUESTIONS: 1
ENABLE_NP_FACTS: 1
LANGUAGE: EN
FALLBACK_FILE: fallbacks_dream_en.json
