dff-book-sfc-skill:
- group: skills
  connector:
    protocol: http
    timeout: 2.0
    url: http://dff-book-sfc-skill:8034/respond
  dialog_formatter: state_formatters.dp_formatters:dff_book_sfc_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
