sentence-ranker:
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://sentence-ranker:8128/respond
  dialog_formatter: state_formatters.dp_formatters:sentence_ranker_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
sentence-ranker-multilingual:
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 1.0
    url: http://sentence-ranker-multilingual:8128/respond
  dialog_formatter: state_formatters.dp_formatters:sentence_ranker_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
