# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  files:
    ports:
      - 3000:3000
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
  teams-postprocessor:
    volumes:
      - "./annotators/teams_postprocessor:/src"
      - "./common:/src/common"
    ports:
      - 8019:8019
  llm-based-response-selector-gpt4:
    volumes:
      - "./response_selectors/llm_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8003:8003
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
    ports:
      - 8087:8087
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 8135:8135
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8145:8145
  openai-api-gpt4:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8159:8159
  dff-general-pm-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8189:8189
  dff-meeting-analysis-skill:
    volumes:
      - "./skills/dff_meeting_analysis_skill:/src"
      - "./common:/src/common"
    ports:
      - 8186:8186
  doc-retriever:
    volumes:
      - "./annotators/doc_retriever:/src"
      - "./common:/src/common"
      - "./documents:/src/documents"
    ports:
      - 8165:8165
  doc-processor-from-atts:
    volumes:
      - "./annotators/doc_processor:/src"
      - "./common:/src/common"
      - "./documents:/src/documents"
    ports:
      - 8188:8188
  dff-document-qa-llm-skill:
    volumes:
      - "./skills/dff_document_qa_llm_skill:/src"
      - "./common:/src/common"
      - "./documents:/src/documents"
    ports:
      - 8166:8166
  llm-based-skill-selector:
    volumes:
      - "./skill_selectors/llm_based_skill_selector:/src"
      - "./common:/src/common"
      - "./components:/src/components"
    ports:
      - 8182:8182
  dff-google-api-skill:
    volumes:
      - "./skills/dff_google_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8162:8162

version: "3.7"
