services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
    ports:
      - ${AGENT_PORT}:4242
  combined-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  sentseg:
  convers-evaluation-selector:
  spelling-preprocessing:
  dff-api-skill:
version: '3.7'
