name: emotion-detection
endpoints:
- model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8040
      SERVICE_NAME: emotion_detection
      VIDEO_PRETRAINED: "microsoft/xclip-base-patch32"
      TEXT_PRETRAINED: "bert-large-uncased"
      MULTIMODAL_MODEL: "final_model.pt"
      REDUNDANT_FEATURES: "redundant_features.txt"
      MODEL_PATH: "/data/"
      PREFIX: "Detect emotions:"
    context: .
    dockerfile: ./annotators/emotion_detection/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8040
  deploy:
    resources:
      limits:
        memory: 1G
      reservations:
        memory: 1G
  environment:
      - CUDA_VISIBLE_DEVICES=0
  ports:
  - 8040:8040